[package]
name = "iot_environmental_hub"
version = "0.3.0"
authors = ["Franco Sarubbi <sarubbi.fe@gmail.com>"]
edition = "2024"
resolver = "2"
rust-version = "1.85"

[[bin]]
name = "iot_environmental_hub"
harness = false # Desactiva el arnés nativo de test para solucionar errores de rust-analyzer


[dependencies]
log = "0.4"
esp-idf-hal = "0.46.2" 
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
embedded-svc = "0.29"
async-channel = "2.3"
embassy-futures = "0.1"
edge-executor = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
anyhow = "1.0"
serde_json = "1.0"

[build-dependencies]
embuild = "0.33"


# ==============================================================================
# PERFILES DE COMPILACIÓN Y CONFIGURACIÓN DE OPTIMIZACIÓN EN ESP32
# ==============================================================================

[profile.dev]
debug = true       # Conserva los símbolos de depuración (no incrementan el tamaño real en la Flash física)
opt-level = 0    

# OPCIÓN 1: Optimización de producción muy agresiva (Mayor velocidad y tamaño controlado)
[profile.release]
opt-level = "s"           # Optimiza reduciendo el tamaño del binario pero manteniendo optimizaciones de rendimiento
lto = true                # Link-Time Optimization: Elimina de forma global el código muerto de todas las dependencias
codegen-units = 1         # Reduce las unidades de generación de código a 1 para permitir que LTO limpie de forma mucho más eficaz
panic = "abort"           # Desactiva el unwinding del stack en pánicos. Reduce drásticamente el tamaño del firmware
strip = true              # Remueve automáticamente todos los símbolos de debug y tablas de secciones del binario final

# OPCIÓN 2: Optimización moderada
# [profile.release]
# opt-level = 2           # Optimización estándar orientada al rendimiento puro (puede aumentar el tamaño del binario final)
# lto = "thin"            # LTO ligero: realiza optimizaciones intermedias sin consumir tanto tiempo en la compilación
# codegen-units = 16      # Permite compilación en paralelo más rápida
# panic = "abort"
# strip = false