idf_component_register(
        SRCS
        "main.c"
        "settings.c"
        "mqtt.c"
        "mq135.c"
        "ky037.c"
        "dht11.c"
        "data.c"
        "wifi.c"
        "time.c"
        "monitor.c"
        "system.c"
        "fsm.c"
        "ota.c"
        "message.c"
        "converter.c"
        "timer.c"
        "healthscore.c"
        "parser.c"
        "heartbeat.c"
        INCLUDE_DIRS
        "."
        REQUIRES
        mbedtls
        esp_driver_rmt
        mpack
)